import React, { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Separator } from "@/components/ui/separator";
import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  ArrowLeft,
  FileText,
  MapPin,
  Calendar,
  AlertCircle,
  Tag,
  Image as ImageIcon,
  Sparkles,
  Download,
  Share2,
  CheckCircle2,
  Send,
  Loader2,
} from "lucide-react";

const ReportSummary: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const report = location.state?.report;
  const [selectedPhoto, setSelectedPhoto] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [submissionData, setSubmissionData] = useState<{
    id: string;
    submittedAt: string;
  } | null>(null);
  const [submitError, setSubmitError] = useState<string | null>(null);

  if (!report) {
    return (
      <div className="min-h-screen flex items-center justify-center p-4 bg-gradient-to-br from-background via-background to-muted/20">
        <Card className="max-w-md w-full">
          <CardHeader className="text-center">
            <div className="mx-auto mb-4 w-16 h-16 rounded-full bg-destructive/10 flex items-center justify-center">
              <AlertCircle className="w-8 h-8 text-destructive" />
            </div>
            <CardTitle>No Report Data</CardTitle>
            <CardDescription>
              No report data was found. Please generate a report first.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button onClick={() => navigate(-1)} className="w-full" variant="outline">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Go Back
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  const getPriorityColor = (priority: string) => {
    switch (priority?.toLowerCase()) {
      case "high":
      case "urgent":
        return "destructive";
      case "medium":
        return "default";
      case "low":
        return "secondary";
      default:
        return "outline";
    }
  };

  const getCategoryIcon = (category: string) => {
    // Add category-specific icons if needed
    return <Tag className="h-4 w-4" />;
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadReport = () => {
    const reportContent = `
CIVIC ISSUE REPORT
==================================================

Report ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}
Date: ${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}

--------------------------------------------------
ISSUE DETAILS
--------------------------------------------------

Title: ${report.title}

Category: ${report.category}
Priority: ${report.priority}

Description:
${report.description}

--------------------------------------------------
LOCATION INFORMATION
--------------------------------------------------

Address: ${report.address}
Coordinates: ${report.location?.lat}, ${report.location?.lng}
Google Maps: https://www.google.com/maps?q=${report.location?.lat},${report.location?.lng}

--------------------------------------------------
OFFICIAL REPORT SUMMARY
--------------------------------------------------

${sanitizeSummary(report.aiSummary || "No summary available")}

--------------------------------------------------
SUBMISSION NOTES
--------------------------------------------------

- This report is ready for submission to local authorities
- All details have been verified and formatted professionally
- Location coordinates and evidence are available
${report.photos && report.photos.length > 0 ? `- ${report.photos.length} photo(s) attached as evidence` : ''}

==================================================
Generated by CodeMeet - Civic Issue Reporting Platform
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Civic_Report_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: report.title,
          text: report.description,
        });
      } catch (err) {
        console.log("Error sharing:", err);
      }
    } else {
      // Fallback: copy to clipboard
      const reportText = `${report.title}\n\n${report.description}\n\nCategory: ${report.category}\nPriority: ${report.priority}\nAddress: ${report.address}`;
      navigator.clipboard.writeText(reportText);
      alert("Report details copied to clipboard!");
    }
  };

  const handleSubmitToAuthorities = async () => {
    setIsSubmitting(true);
    setSubmitError(null);

    try {
      // Ensure coordinates are numbers
      const lng = typeof report.location.lng === 'number' 
        ? report.location.lng 
        : parseFloat(report.location.lng);
      const lat = typeof report.location.lat === 'number' 
        ? report.location.lat 
        : parseFloat(report.location.lat);

      // Prepare data for submission
      const issueData = {
        title: report.title,
        description: report.description,
        category: report.category.toLowerCase(),
        priority: report.priority.toLowerCase(),
        location: {
          type: 'Point' as const,
          coordinates: [lng, lat], // MongoDB expects [lng, lat]
          address: report.address,
        },
        images: report.photos || [],
        aiSummary: report.aiSummary,
        submissionStatus: 'submitted' as const,
      };

      console.log('Submitting issue data:', issueData);


  // Get JWT token from localStorage using the correct key
  const token = localStorage.getItem('jan_awaaz_token');

      const response = await fetch('/api/issues', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { 'Authorization': `Bearer ${token}` } : {}),
        },
        body: JSON.stringify(issueData),
      });

      const data = await response.json();
      console.log('Response:', response.status, data);
      
      // Log detailed error information
      if (!response.ok) {
        console.error('Submit Error Details:', {
          status: response.status,
          message: data.message,
          errors: data.errors,
          sentData: issueData
        });
      }

      if (response.ok && data.success) {
        setIsSubmitted(true);
        setSubmissionData({
          id: data.data.issue._id,
          submittedAt: data.data.issue.submittedAt || new Date().toISOString(),
        });
      } else {
        const errorMessage = data.errors 
          ? data.errors.map((e: any) => e.msg).join(', ')
          : data.message || 'Failed to submit report. Please try again.';
        setSubmitError(errorMessage);
      }
    } catch (error) {
      console.error('Submission error:', error);
      setSubmitError('Network error. Please check your connection and try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-muted/20 py-8 px-4">
      <div className="max-w-5xl mx-auto space-y-6">
        {/* Header Section */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <Button
            onClick={() => navigate(-1)}
            variant="ghost"
            className="gap-2"
          >
            <ArrowLeft className="h-4 w-4" />
            Back
          </Button>
          
          <div className="flex gap-2 flex-wrap">
            <Button onClick={handleShare} variant="outline" size="sm" className="gap-2">
              <Share2 className="h-4 w-4" />
              Share
            </Button>
            <Button onClick={handleDownloadReport} variant="outline" size="sm" className="gap-2">
              <Download className="h-4 w-4" />
              Download
            </Button>
            <Button onClick={handlePrint} variant="outline" size="sm" className="gap-2">
              <FileText className="h-4 w-4" />
              Print
            </Button>
          </div>
        </div>

        {/* Submit Button Section */}
        {!isSubmitted && (
          <Card className="border-primary/50 bg-gradient-to-r from-primary/5 to-primary/10">
            <CardContent className="pt-6">
              <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
                <div className="flex-1 text-center sm:text-left">
                  <h3 className="text-lg font-semibold mb-1">Ready to Submit?</h3>
                  <p className="text-sm text-muted-foreground">
                    Submit this report to local authorities for review and action
                  </p>
                </div>
                <Button
                  onClick={handleSubmitToAuthorities}
                  disabled={isSubmitting}
                  size="lg"
                  className="gap-2 min-w-[200px]"
                >
                  {isSubmitting ? (
                    <>
                      <Loader2 className="h-5 w-5 animate-spin" />
                      Submitting...
                    </>
                  ) : (
                    <>
                      <Send className="h-5 w-5" />
                      Submit to Authorities
                    </>
                  )}
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Error Alert */}
        {submitError && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{submitError}</AlertDescription>
          </Alert>
        )}

        {/* Success Alert */}
        {isSubmitted && submissionData && (
          <Card className="border-green-500 bg-gradient-to-r from-green-50 to-emerald-50 dark:from-green-950 dark:to-emerald-950">
            <CardContent className="pt-6">
              <div className="text-center space-y-4">
                <div className="mx-auto w-16 h-16 rounded-full bg-green-500 flex items-center justify-center">
                  <CheckCircle2 className="w-8 h-8 text-white" />
                </div>
                <div>
                  <h3 className="text-2xl font-bold text-green-700 dark:text-green-400 mb-2">
                    Report Successfully Submitted!
                  </h3>
                  <p className="text-muted-foreground mb-4">
                    Your civic issue report has been submitted to local authorities
                  </p>
                  <div className="inline-flex flex-col gap-2 bg-white dark:bg-gray-900 p-4 rounded-lg border">
                    <div className="flex items-center gap-2 text-sm">
                      <span className="font-semibold">Report ID:</span>
                      <code className="px-2 py-1 bg-muted rounded text-primary font-mono">
                        #{submissionData.id.slice(-8).toUpperCase()}
                      </code>
                    </div>
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <Calendar className="h-4 w-4" />
                      <span>
                        {new Date(submissionData.submittedAt).toLocaleString('en-IN', {
                          dateStyle: 'full',
                          timeStyle: 'short',
                        })}
                      </span>
                    </div>
                  </div>
                </div>
                <div className="flex gap-3 justify-center pt-2">
                  <Button
                    variant="outline"
                    onClick={() => navigate('/communities')}
                    className="gap-2"
                  >
                    <FileText className="h-4 w-4" />
                    View All Reports
                  </Button>
                  <Button
                    onClick={() => navigate('/home')}
                    className="gap-2"
                  >
                    Submit Another Report
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Success Alert - Simplified version at top */}
        {isSubmitted ? (
          <Alert className="border-green-500/50 bg-green-500/10">
            <CheckCircle2 className="h-4 w-4 text-green-600" />
            <AlertDescription className="text-green-700 dark:text-green-400">
              Report submitted successfully! Authorities have been notified.
            </AlertDescription>
          </Alert>
        ) : (
          <Alert className="border-green-500/50 bg-green-500/10">
            <CheckCircle2 className="h-4 w-4 text-green-600" />
            <AlertDescription className="text-green-700 dark:text-green-400">
              Report successfully generated! Review the details below.
            </AlertDescription>
          </Alert>
        )}

        {/* Main Title Card */}
        <Card className="border-2 shadow-lg">
          <CardHeader className="space-y-4">
            <div className="flex items-start justify-between gap-4">
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-2">
                  <Sparkles className="h-5 w-5 text-primary" />
                  <span className="text-sm font-medium text-muted-foreground">
                    AI-Generated Report
                  </span>
                </div>
                <CardTitle className="text-3xl font-bold leading-tight">
                  {report.title}
                </CardTitle>
              </div>
              <Badge variant={getPriorityColor(report.priority)} className="text-sm px-3 py-1">
                {report.priority} Priority
              </Badge>
            </div>
            <div className="flex flex-wrap gap-2">
              <Badge variant="outline" className="gap-1">
                {getCategoryIcon(report.category)}
                {report.category}
              </Badge>
              <Badge variant="outline" className="gap-1">
                <Calendar className="h-3 w-3" />
                {new Date().toLocaleDateString()}
              </Badge>
            </div>
          </CardHeader>
        </Card>

        {/* Tabs Section */}
        <Tabs defaultValue="overview" className="w-full">
          <TabsList className="grid w-full grid-cols-3 lg:w-auto">
            <TabsTrigger value="overview" className="gap-2">
              <FileText className="h-4 w-4" />
              Overview
            </TabsTrigger>
            <TabsTrigger value="location" className="gap-2">
              <MapPin className="h-4 w-4" />
              Location
            </TabsTrigger>
            <TabsTrigger value="media" className="gap-2">
              <ImageIcon className="h-4 w-4" />
              Media
            </TabsTrigger>
          </TabsList>

          {/* Overview Tab */}
          <TabsContent value="overview" className="space-y-4 mt-6">
            <Card>
              <CardHeader>
                <CardTitle className="text-xl">Description</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground leading-relaxed">
                  {report.description}
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-xl flex items-center gap-2">
                  <FileText className="h-5 w-5 text-primary" />
                  Official Report Summary
                </CardTitle>
                <CardDescription>
                  Formatted for government submission
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {/* Official Header */}
                  <div className="border-b-2 border-primary/20 pb-4">
                    <p className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">
                      Civic Issue Report
                    </p>
                    <p className="text-xs text-muted-foreground mt-1">
                      Report ID: {Math.random().toString(36).substr(2, 9).toUpperCase()} | Date: {new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}
                    </p>
                  </div>

                  {/* Main Content */}
                  <div className="bg-gradient-to-br from-primary/5 to-primary/10 p-6 rounded-lg border border-primary/20">
                    <div className="prose prose-sm max-w-none">
                      <p className="whitespace-pre-line leading-relaxed text-foreground">
                        {report.aiSummary
                          ? sanitizeSummary(report.aiSummary)
                          : "No summary generated yet."}
                      </p>
                    </div>
                  </div>

                  {/* Official Footer */}
                  <div className="border-t border-border pt-4 text-xs text-muted-foreground">
                    <p className="font-medium mb-1">Report Submission Information:</p>
                    <ul className="list-disc list-inside space-y-1 ml-2">
                      <li>This report is ready for submission to local authorities</li>
                      <li>All details have been verified and formatted professionally</li>
                      <li>Location coordinates and evidence are attached</li>
                    </ul>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Location Tab */}
          <TabsContent value="location" className="space-y-4 mt-6">
            <Card>
              <CardHeader>
                <CardTitle className="text-xl flex items-center gap-2">
                  <MapPin className="h-5 w-5" />
                  Location Details
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <div className="flex items-start gap-3 p-4 rounded-lg bg-muted/50">
                    <MapPin className="h-5 w-5 text-primary mt-0.5" />
                    <div className="flex-1">
                      <p className="font-medium mb-1">Address</p>
                      <p className="text-muted-foreground">{report.address}</p>
                    </div>
                  </div>
                  
                  {report.location && (
                    <div className="grid sm:grid-cols-2 gap-3">
                      <div className="p-4 rounded-lg bg-muted/50">
                        <p className="text-sm text-muted-foreground mb-1">Latitude</p>
                        <p className="font-mono font-medium">{report.location.lat}</p>
                      </div>
                      <div className="p-4 rounded-lg bg-muted/50">
                        <p className="text-sm text-muted-foreground mb-1">Longitude</p>
                        <p className="font-mono font-medium">{report.location.lng}</p>
                      </div>
                    </div>
                  )}
                </div>

                <Separator />

                <div className="pt-2">
                  <Button variant="outline" className="w-full gap-2" asChild>
                    <a
                      href={`https://www.google.com/maps?q=${report.location?.lat},${report.location?.lng}`}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <MapPin className="h-4 w-4" />
                      Open in Google Maps
                    </a>
                  </Button>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Media Tab */}
          <TabsContent value="media" className="space-y-4 mt-6">
            <Card>
              <CardHeader>
                <CardTitle className="text-xl flex items-center gap-2">
                  <ImageIcon className="h-5 w-5" />
                  Attached Photos
                </CardTitle>
                <CardDescription>
                  {report.photos && report.photos.length > 0
                    ? `${report.photos.length} photo(s) attached to this report`
                    : "No photos attached"}
                </CardDescription>
              </CardHeader>
              <CardContent>
                {report.photos && report.photos.length > 0 ? (
                  <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                    {report.photos.map((url: string, idx: number) => (
                      <div
                        key={idx}
                        className="relative group cursor-pointer overflow-hidden rounded-lg border-2 border-border hover:border-primary transition-all duration-300"
                        onClick={() => setSelectedPhoto(url)}
                      >
                        <img
                          src={url}
                          alt={`Photo ${idx + 1}`}
                          className="w-full h-48 object-cover transition-transform duration-300 group-hover:scale-110"
                        />
                        <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors duration-300 flex items-center justify-center">
                          <span className="opacity-0 group-hover:opacity-100 text-white font-medium bg-black/50 px-3 py-1 rounded-full text-sm">
                            View Full
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-12 text-muted-foreground">
                    <ImageIcon className="h-12 w-12 mx-auto mb-3 opacity-50" />
                    <p>No photos attached to this report</p>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>

        {/* Photo Modal */}
        {selectedPhoto && (
          <div
            className="fixed inset-0 z-50 bg-black/90 flex items-center justify-center p-4"
            onClick={() => setSelectedPhoto(null)}
          >
            <div className="relative max-w-4xl max-h-[90vh]">
              <Button
                variant="ghost"
                size="icon"
                className="absolute -top-12 right-0 text-white hover:text-white hover:bg-white/20"
                onClick={() => setSelectedPhoto(null)}
              >
                ✕
              </Button>
              <img
                src={selectedPhoto}
                alt="Full size"
                className="max-w-full max-h-[90vh] object-contain rounded-lg"
              />
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

// Utility to clean and format AI summary for official report
function sanitizeSummary(text: string) {
  if (!text) return "";

  // Remove emojis
  let cleaned = text.replace(/[\u{1F600}-\u{1F6FF}\u{1F300}-\u{1F5FF}\u{1F700}-\u{1F77F}\u{1F900}-\u{1F9FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gu, '');
  
  // Remove conversational intro phrases
  cleaned = cleaned.replace(/^(Certainly!?|Sure!?|Here's|Here is).+?(:|\n)/i, '');
  
  // Remove "Next Step" and everything after it
  const nextStepIndex = cleaned.search(/\n\s*(Next Step|Need help|Let me know|This is your civic voice)/i);
  if (nextStepIndex !== -1) {
    cleaned = cleaned.substring(0, nextStepIndex);
  }
  
  // Remove lines with URLs or links
  cleaned = cleaned.replace(/.*\[?https?:\/\/[^\]]+\]?.*/gi, '');
  
  // Remove lines with "Submit this report"
  cleaned = cleaned.replace(/.*Submit this report.*/gi, '');
  
  // Remove lines with app suggestions
  cleaned = cleaned.replace(/.*Civic App.*/gi, '');
  cleaned = cleaned.replace(/.*ward office.*/gi, '');
  
  // Remove markdown formatting
  cleaned = cleaned.replace(/[\*#`]/g, '');
  
  // Remove multiple dashes/separators
  cleaned = cleaned.replace(/\n\s*[-—]{3,}\s*\n/g, '\n\n');
  
  // Remove extra whitespace and blank lines
  cleaned = cleaned.replace(/\n{3,}/g, '\n\n');
  cleaned = cleaned.trim();
  
  return cleaned;
}

export default ReportSummary;